"""empty message

Revision ID: 4de35200d913
Revises: 789149ae7639
Create Date: 2021-03-26 13:57:35.157607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4de35200d913'
down_revision = '789149ae7639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('likes_likes_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('likes', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_likes_fkey', 'likes', 'users', ['likes'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###
