"""empty message

Revision ID: 52ec25eec86d
Revises: e22c91330742
Create Date: 2021-03-24 21:57:42.554552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52ec25eec86d'
down_revision = 'e22c91330742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('likes', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'tweets', 'users', ['likes'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'likes')
    # ### end Alembic commands ###
