"""empty message

Revision ID: 66048cdfcde0
Revises: 7fdf6e844d9a
Create Date: 2021-03-25 19:37:06.548901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66048cdfcde0'
down_revision = '7fdf6e844d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('tweet_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('likes', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['likes'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    op.drop_column('tweets', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('likes', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_table('likes')
    # ### end Alembic commands ###
