"""empty message

Revision ID: 7fdf6e844d9a
Revises: 625db4d77e8b
Create Date: 2021-03-25 16:56:05.147145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fdf6e844d9a'
down_revision = '625db4d77e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'likes',
               existing_type=postgresql.UUID(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'likes',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
